version: '3.7'
services:
  web-app:
    image: my-web-app
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - CATALINA_OPTS=-DJDBC_DATABASE_URL="jdbc:postgresql://db:5432/db?user=app&password=pass"
    depends_on:
      - db
  db:
    image: postgres:13-alpine3.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
