###
# moderator token
GET https://localhost:8443/api/cards.getAll
Authorization: PgKam1JWhAvmaZT06RkRgay0E08jOOYC2YbDuIsbg+3ATgEvrDit6idDYIKi6vc8m/XdSWseDX9vMvwWewhaXw==

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
POST https://localhost:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "moderator",
  "password": "god"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("login_token", response.body.token);
});
%}

###

GET https://localhost:8443/api/cards.getAll
Authorization: {{login_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


###
# Registration
# HTTP Status 500 – Internal Server Error
POST https://localhost:8443/api/rest/users/register
Content-Type: application/json

{
  "username": "moderator",
  "password": "moderator"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 500, "Response status is not 500");
  client.global.set("registration_token", response.body.token);
});
%}
