###
# user token
GET https://localhost:8443/api/cards.getAll
Authorization: hp2dqW7TyVkXP34ieOjtBYbBJ7K0TOn8FsyC5RfUysUoEmhomH4UoCilK09Ttt/oNu0bGU2vTW9G4Si9iT261w==


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
POST https://localhost:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "student",
  "password": "qwery123"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("login_token", response.body.token);
});
%}

###

GET https://localhost:8443/api/cards.getAll
Authorization: {{login_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
# Registration
# HTTP Status 500 – Internal Server Error
POST https://localhost:8443/api/rest/users/register
Content-Type: application/json

{
  "username": "student",
  "password": "student"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 500, "Response status is not 500");
  client.global.set("registration_token", response.body.token);
});
%}
